version: "3.9"

services:
  web:
    build: ./web
    depends_on:
      - db
      - mail
    volumes:
      - ./web/:/var/www/html
    ports:
      - "${APP_PORT}:80"
    env_file:
      - .env


  db:
    image: mariadb:10.6.4
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    restart: always
    volumes:
      - /var/lib/mysql
      - ./db/:/etc/mysql

  dbadmin:
    image: adminer:4.8.1
    ports:
      - "${DB_ADMIN_PORT}:8080"
    environment:
      - PMA_HOST=db
    depends_on:
      - db


  mail:
    image: maildev/maildev:latest
    ports:
      - "${MAIL_ADMIN_PORT}:80"
